### ISSUE TITLE
@kampffrosch94 Sorry for creating an issue. Can I get your Discord/any social? 

### ISSUE THREAD

**Issue by DesKamori** [kampffrosch94/jpdb-deck-manager#1]
@kampffrosch94 
Again, sorry for creating an issue, but I've only managed to find your github. Can we hook up on Discord? I really want to ask you some questions about how to use jpdb, and about your japanese learning in general. My discord nickname is "deskamori", and my email is andrey22387@gmail.com
I'll be very grateful if you'll reply.

**Comment by kampffrosch94** [comment]
You can find me (and others) on the official jpdb discord
https://discord.gg/jWwVD7D2sZ
