### ISSUE TITLE
Deck learning coverage and coverage do not update on CoverageOverview

### ISSUE THREAD

**Issue by keian-dev** [kampffrosch94/jpdb-deck-manager#2]
I deployed the app locally and performed reviews on JPDB which increased my learning and known coverage.
The app updates my coverage to match what is shown on the decks list on JPDB.io for all components except CoverageOverview

I have a fix which I can submit if you're interested

**Comment by kampffrosch94** [comment]
Thanks for reporting this.
It should be fixed with 8345b9d
